name: CI

# This workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

jobs:
  linux:
    name: Linux
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler_version: [14]
        option_proxyfmu: ['proxyfmu=True', 'proxyfmu=False']
    runs-on: ubuntu-latest
    container:
      image: gcc:${{ matrix.compiler_version }}

    steps:
      - uses: actions/checkout@v6
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y pipx cmake doxygen
          pipx install conan
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Configure Conan
        run: |
          conan profile detect
          conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-local
      - name: Build
        run: |
          conan install . -s build_type=${{ matrix.build_type }} -o "libcosim/*:${{ matrix.option_proxyfmu }}" --build=missing
          cmake -S . -B build/${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build/${{ matrix.build_type }}
          cmake --build build/${{ matrix.build_type }} --target install
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: cosim-${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.compiler_version }}-${{ matrix.option_proxyfmu }}
          path: build/${{ matrix.build_type }}/dist
          overwrite: true

  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        build_type: [Debug, Release]
        option_proxyfmu: ['proxyfmu=True', 'proxyfmu=False']

    steps:
      - uses: actions/checkout@v6
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan
      - name: Configure Conan
        run: |
          conan profile detect
          conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-local --force
      - name: Build
        run: |
          conan install . -s build_type=${{ matrix.build_type }} -o "libcosim/*:${{ matrix.option_proxyfmu }}" --build=missing
          cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
          cmake --build build --config ${{ matrix.build_type }}
          cmake --build build --config ${{ matrix.build_type }} --target install
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: cosim-${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.option_proxyfmu }}
          path: build/dist
          overwrite: true
